# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [8]:
import numpy as np

In [9]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [10]:
np.array(my_list)

array([1, 2, 3])

matrix for 2D array - list of lists

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

works same as python range function - starts with 1st number and goes up to but does not include final number

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

can also specify step between each number in range

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

not to be confused with range - linspace 3rd argument is number of values you want in array

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

identity matrix useful in linear algebra - 2D matrix where # of rows = # of columns - square - has diagonal of 1s and rest are 0

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [22]:
np.random.rand(2)

array([0.15264565, 0.27314099])

if you want 2D matrix, pass in 2 values

In [23]:
np.random.rand(5,5)

array([[0.90097335, 0.97368403, 0.84054948, 0.82897777, 0.63231127],
       [0.3459924 , 0.61490126, 0.68147606, 0.81272482, 0.56632502],
       [0.16508221, 0.60409824, 0.0767294 , 0.13268749, 0.42271396],
       [0.8090206 , 0.50738892, 0.67907614, 0.27995363, 0.54348261],
       [0.12441685, 0.26411282, 0.2188301 , 0.2318734 , 0.65573086]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [24]:
np.random.randn(2)

array([1.87937886, 1.80501504])

In [25]:
np.random.randn(5,5)

array([[ 0.99212637, -1.03977665, -0.64296404,  0.98048426,  0.7615178 ],
       [ 1.63656559,  0.77985583,  1.58769297, -0.96766591, -1.27329294],
       [-1.22109046,  0.32348649, -0.08098424,  1.24020883, -0.80344902],
       [-0.52541391, -1.26278005,  0.50090513, -0.01694874,  2.43869641],
       [ 0.60828759, -1.54882197,  2.0403483 , -0.97102079,  1.73949998]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [26]:
np.random.randint(1,100)

53

for list of random integers, pass number of values you want as 3rd argument

In [27]:
np.random.randint(1,100,10)

array([ 7, 53, 38, 90, 82, 25, 36, 77, 59, 37])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

In [ ]:
ranarr

## Reshape
Returns an array containing the same data with a new shape.

NOTE: if you select dimensions that your array can't fill, you'll get an error because the total size of the new array must be unchanged

In [ ]:
arr.reshape(5,5)

In [ ]:
arr.reshape(5,10)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

In [ ]:
ranarr.max()

to find index location of max value

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.min()

to return index location of min value

In [ ]:
ranarr.argmin()

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)

In [ ]:
arr.reshape(25,1).shape

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

if you wanted to not have to call np.random.whatever - can import function itself 

In [ ]:
from numpy.random import randint

In [ ]:
randint(2,10)

# Great Job!