# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
# declare a python list
my_list = [1,2,3]
# print the list
my_list

[1, 2, 3]

In [3]:
# convert the list to a numpy array
np.array(my_list)

array([1, 2, 3])

matrix for 2D array - list of lists

In [4]:
# create a 2D python list (a list of lists)
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
# print the 2D list
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
# convert the 2D list to a numpy array
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

works same as python range function - starts with 1st number and goes up to but does not include final number

In [6]:
# create a numpy array with values from 0 to 9
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

can also specify step between each number in range

In [7]:
# create a numpy array with values from 0 to 10 with a step of 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [8]:
# create a numpy array of zeros with length 3
np.zeros(3)

array([0., 0., 0.])

In [9]:
# create a 2D numpy array of zeros with shape (5,5)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# create a numpy array of ones with length 3
np.ones(3)

array([1., 1., 1.])

In [11]:
# create a 2D numpy array of ones with shape (3,3)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

not to be confused with range - linspace 3rd argument is number of values you want in array

In [12]:
# create a numpy array of 3 evenly spaced numbers between 0 and 10
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
# create a numpy array of 50 evenly spaced numbers between 0 and 10
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

identity matrix useful in linear algebra - 2D matrix where # of rows = # of columns - square - has diagonal of 1s and rest are 0

In [14]:
# create a 4x4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [15]:
# create a numpy array of 2 random numbers between 0 and 1
np.random.rand(2)

array([0.95722653, 0.06609515])

if you want 2D matrix, pass in 2 values

In [16]:
# create a 5x5 array of random numbers between 0 and 1
np.random.rand(5,5)

array([[0.73941387, 0.79486916, 0.46194251, 0.55753042, 0.70266631],
       [0.35546516, 0.37939238, 0.00334944, 0.61604523, 0.35544767],
       [0.95341525, 0.80903884, 0.42498142, 0.97415221, 0.04463791],
       [0.05786963, 0.26958085, 0.5618339 , 0.63051347, 0.77636424],
       [0.57166691, 0.40437817, 0.21726537, 0.5298189 , 0.0967046 ]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [17]:
# create a numpy array of 2 random numbers sampled from a standard normal distribution
np.random.randn(2)

array([1.64237473, 0.28195718])

In [18]:
# create a 5x5 array of random numbers sampled from a standard normal distribution
np.random.randn(5,5)

array([[-1.99379387,  0.29135843, -0.84056199, -0.84272157,  0.60496673],
       [-1.86530968, -0.18536343, -0.03099162,  1.93318339, -1.44423803],
       [-1.08375721,  0.16113217,  0.61531565, -1.45662775, -0.23311948],
       [ 0.00369322,  0.97177065, -2.83927815,  0.44782763,  0.74602706],
       [ 0.61876819,  0.51533182,  0.62315149,  0.5205589 ,  0.24799888]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [19]:
# print a random integer between 0 and 10
np.random.randint(0,11)
# create an array of 10 random integers between 0 and 50
np.random.randint(0,50,10)

array([29, 44, 17,  3, 13, 25, 30, 42, 40, 26])

for list of random integers, pass number of values you want as 3rd argument

In [20]:
# create a numpy array of 10 random integers between 1 and 100
np.random.randint(1,100,10)

array([22,  3, 77, 58, 44, 29, 37, 32, 62, 42])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [21]:
# create a numpy array of 25 numbers between 0 and 24
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
# print the 25 numbers between 0 and 24
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
# print the 10 random integers between 0 and 50
ranarr

array([33, 41, 30, 21, 30, 18, 33,  7, 10, 45])

## Reshape
Returns an array containing the same data with a new shape.

NOTE: if you select dimensions that your array can't fill, you'll get an error because the total size of the new array must be unchanged

In [24]:
# reshape the array of 25 numbers into a 5x5 array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
# reshape the array of 25 numbers into a 5x10 array (this will throw an error because the total number of elements is not the same)
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [26]:
# print the 10 random integers between 0 and 50
ranarr

array([33, 41, 30, 21, 30, 18, 33,  7, 10, 45])

In [27]:
# find the maximum value in the array of 10 random integers
ranarr.max()

np.int64(45)

to find index location of max value

In [28]:
# find the index of the maximum value in the array of 10 random integers
ranarr.argmax()

np.int64(9)

In [29]:
# find the minimum value in the array of 10 random integers
ranarr.min()

np.int64(7)

to return index location of min value

In [30]:
# find the index of the minimum value in the array of 10 random integers
ranarr.argmin()

np.int64(7)

## Shape

Shape is an attribute that arrays have (not a method):

In [31]:
# Vector
arr.shape

(25,)

In [32]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
# Notice the shape has changed
arr.reshape(1,25).shape

(1, 25)

In [34]:
# Notice the shape has changed
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [35]:
# Notice the shape has changed
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [36]:
# print the data type of the array
arr.dtype

dtype('int64')

if you wanted to not have to call np.random.whatever - can import function itself 

In [37]:
# create an array of 10 random integers between 0 and 50
from numpy.random import randint

In [38]:
# create an array of 10 random integers between 2 and 10
randint(2,10)

6

# Great Job!